- platform: Instagram
  url: https://instagram.com/lazyperfectionist_official
  handle: "@lazyperfectionist_official"
- platform: TikTok
  url: https://tiktok.com/@lazyperfectionist_official
  handle: "@lazyperfectionist_official"
- platform: YouTube
  url: https://youtube.com/watch?v=Hw2a43RV1p0
  handle: Orbit (Official)