name: Sync Medium
on:
  schedule:
    - cron: '0 * * * *'  # Hourly
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Medium RSS
        run: |
          curl "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@your-medium-handle" > medium.json
          node -e "
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('medium.json'));
          data.items.slice(0,10).forEach(p => {
            const date = new Date(p.pubDate).toISOString().split('T')[0];
            const slug = p.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
            const path = '_posts/' + date + '-' + slug + '.md';
            if (!fs.existsSync(path)) {
              const content = '---\n' +
                'title: \"' + p.title.replace(/\"/g, '\\\"') + '\"\n' +
                'date: ' + date + '\n' +
                'categories: [medium]\n' +
                '---\n\n' +
                '<div class=\"medium-embed\"><a href=\"' + p.link + '\">Read on Medium →</a></div>\n\n' +
                p.description.replace(/<[^>]*>/g, '').substring(0,300) + '...';
              fs.writeFileSync(path, content);
            }
          });
          "
      - name: Commit
        run: |
          git config user.name "Medium Sync"
          git config user.email "action@github.com"
          git add .
          git diff --quiet || git commit -m "Sync Medium posts"
          git push